### ISSUE TITLE
Variety Settings take too long to load

### ISSUE THREAD

**Issue by akxer** [peterlevi/variety-slideshow#7]
The Variety settings do not load at all until I close all the Variety processes. Once I kill the process and start loading it from the command line I can see the following screen over the time of `18 minutes` from command to actual opening of the window(The window has not opened yet).

```
ERROR: 2018-03-17 19:35:46,133: reload_config() 'Could not create Downloader for type 19, location Recommended by Variety. Adapts to your taste as you mark images as favorite or trash.'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 420, in reload_config
    dlr = self.create_downloader(type, location)
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 555, in create_downloader
    raise Exception('No Smart user yet, not a problem')
Exception: No Smart user yet, not a problem
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:854: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:854: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:854: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ERROR: 2018-03-17 19:37:56,517: _run() 'sync: Could not load or create smart user'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 516, in _run
    self.load_user(create_if_missing=True)
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 128, in load_user
    self.new_user()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 136, in new_user
    self.user = Util.fetch_json(Smart.API_URL + '/newuser')
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 534, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/newuser (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fccf4113b50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
ERROR: 2018-03-17 19:38:16,997: reporting_thread_method() 'Stats: Could not report config'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 999, in reporting_thread_method
    self.smart.stats_report_config()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 851, in stats_report_config
    res = Util.fetch_json(Smart.API_URL + '/stats/%s/report-config' % statsid, data=data)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 534, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/stats/n6my5l1j7l/report-config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fccb01bd5d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
ERROR: 2018-03-17 19:40:56,740: reporting_thread_method() 'Stats: Could not report config'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 999, in reporting_thread_method
    self.smart.stats_report_config()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 851, in stats_report_config
    res = Util.fetch_json(Smart.API_URL + '/stats/%s/report-config' % statsid, data=data)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 534, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/stats/n6my5l1j7l/report-config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fccf4113c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/variety/PreferencesVarietyDialog.py", line 1078, in _f
    self.parent.smart.load_user(create_if_missing=True)
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 128, in load_user
    self.new_user()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 136, in new_user
    self.user = Util.fetch_json(Smart.API_URL + '/newuser')
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 534, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/newuser (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fccb01e6250>: Failed to establish a new connection: [Errno 110] Connection timed out',))

ERROR: 2018-03-17 19:43:36,485: reporting_thread_method() 'Stats: Could not report config'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 999, in reporting_thread_method
    self.smart.stats_report_config()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 851, in stats_report_config
    res = Util.fetch_json(Smart.API_URL + '/stats/%s/report-config' % statsid, data=data)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 534, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/stats/n6my5l1j7l/report-config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fccb029de50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:854: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ERROR: 2018-03-17 19:46:40,805: _run() 'sync: Could not load or create smart user'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 516, in _run
    self.load_user(create_if_missing=True)
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 128, in load_user
    self.new_user()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 136, in new_user
    self.user = Util.fetch_json(Smart.API_URL + '/newuser')
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 534, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/newuser (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fccb0336210>: Failed to establish a new connection: [Errno 110] Connection timed out',))
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:854: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

System Info: 
Ubuntu 17.10(2 users both using variety), 16GB RAM, Intel Core i7 6700HQ. 
Please ask if any more info is required

*OK, it seems that this thing is taking too long to start, I am posting this thing now at 2:23 PM UTC will keep you updated*

**Comment by akxer** [comment]
Ok, it seems that removing the variety config from `~/.config/variety` solved the problem
